FROM node:14-alpine

RUN mkdir -p /app/web-server
WORKDIR /app/web-server

COPY ./ ./
RUN npm install

# CMD ["npm", "run", "start-dev"] #Start server in development mode
CMD ["npm", "start"] #Start server for production