version: '3'

services:
    ui:
        image: ui
        container_name: ui
        build: 
            context: ./ui
        volumes:
            - ./ui:/app/ui # only for development
        restart: on-failure

    web-server:
        image: web-server
        container_name: web-server
        build: 
            context: ./web-server
        volumes:
            - ./web-server:/app/web-server # only for development
        restart: on-failure

    reverse-proxy:
        image: reverse-proxy
        container_name: reverse-proxy
        build:
            context: ./reverse-proxy
        ports:
            - 80:80
        restart: always
        depends_on:
            - ui
            - web-server

networks:
    app-network:
        driver: bridge