version: '3'

services:
    ui:
        image: ui
        container_name: ui
        build: 
            context: ./ui
        networks: 
            - mynetwork    
        # volumes:
        #     - ./ui:/app/ui # only for development
        restart: on-failure

    web-server:
        image: web-server
        container_name: web-server
        build: 
            context: ./web-server
        networks: 
            - mynetwork
        # volumes:
        #     - ./web-server:/app/web-server # only for development
        restart: on-failure

    auth-service:
        image: auth-service
        container_name: auth-service
        build: 
            context: ./auth-service
        networks: 
            - mynetwork
        # volumes:
        #     - ./auth-service:/app/auth-service # only for development
        restart: on-failure

    reverse-proxy:
        image: reverse-proxy
        container_name: reverse-proxy
        build:
            context: ./reverse-proxy
        ports:
            - 80:80
        networks: 
            - mynetwork
        restart: always
        depends_on:
            - ui
            - web-server
            - auth-service

networks:
    mynetwork:
        driver: bridge