FROM alpine:3.14

WORKDIR /app/ui

RUN apk add --update npm

COPY ./ ./
RUN npm install

############################
# Run a development build
############################

# CMD [ "npm", "start" ]

############################
# Create a production build
############################

RUN npm run build

# Serving static files in production
FROM nginx:1.21.0-alpine

RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

WORKDIR /app/ui
COPY --from=0 /app/ui/dist/ui/* ./

############################
# End of production build
############################