FROM node:14-alpine

RUN mkdir -p /app/ui
WORKDIR /app/ui

COPY ./ ./
RUN npm install
RUN npm run build

FROM nginx:1.21.0-alpine

RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf